from array import array

a = array('i', [10, 20, 30, 40, 50])


print("****************************************************")
print("Original array:", a)
print("****************************************************")
a.append(60)
print("append(60):", a)
print("****************************************************")
print("buffer_info():", a.buffer_info())
print("****************************************************")
b = array('i', [1, 2, 3])
b.byteswap()
print("byteswap():", b)
print("****************************************************")
print("count(20):", a.count(20))
print("****************************************************")
a.extend([70, 80])
print("extend([70, 80]):", a)
print("****************************************************")
c = array('i')
c.frombytes(a.tobytes())
print("frombytes():", c)
print("****************************************************")
with open("numbers.bin", "wb") as f:
    a.tofile(f)
print("****************************************************")
d = array('i')
with open("numbers.bin", "rb") as f:
    d.fromfile(f, len(a))
print("****************************************************")
print("fromfile():", d)
print("****************************************************")
e = array('i')
e.fromlist([100, 200, 300])
print("fromlist():", e)
print("****************************************************")
u = array('u')
u.fromunicode("Hello")
print("fromunicode():", u)
print("****************************************************")
print("index(40):", a.index(40))
print("****************************************************")
a.insert(1, 15)
print("insert(1, 15):", a)
print("****************************************************")
x = a.pop()
print("pop():", x)
print("After pop():", a)
print("****************************************************")
a.remove(20)
print("remove(20):", a)
print("****************************************************")
a.reverse()
print("reverse():", a)
print("****************************************************")
byte_data = a.tobytes()
print("tobytes():", byte_data)
print("****************************************************")
with open("output.bin", "wb") as f:
    a.tofile(f)
print("tofile(): Data written to output.bin")
print("****************************************************")
list_data = a.tolist()
print("tolist():", list_data)
print("****************************************************")
print("tounicode():", u.tounicode())